### ISSUE TITLE
Cadastro do pedido

### ISSUE THREAD

**Issue by LuhOli42** [livnascimento/desafio-m05-b2bt05-equipe-19#10]
Está dando crash no cadastro do produto. N sei se é meu servido ou algo recorrente
a msg de erro

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 587,
  command: 'CONN'
}

Node.js v18.18.2

**Comment by livnascimento** [comment]
Eu acabei de cadastrar esses dois aqui e foi. Também fiz testes sem os campos, com os tipos errados e com um objeto vazio. Testei sem o token mesmo sabendo que se o token quebrasse, quebraria em todos.

![image](https://github.com/livnascimento/desafio-m05-b2bt05-equipe-19/assets/51425339/4790d575-351b-4aae-8936-2760a3153009)
![image](https://github.com/livnascimento/desafio-m05-b2bt05-equipe-19/assets/51425339/83f2bc52-845e-4e9b-affc-432807e4b402)

Salvo engano, pela mensagem de erro, parece ser erro de conexão. Tenta de novo e vê se dá certo, por favor. Qualquer coisa, me retorna aqui ou no whats que faço novos testes amanhã logo, tá?

**Comment by livnascimento** [comment]
Gente, fiz o teste aqui no deploy. Tá funcionando ok. Vou mandar as variáveis do nodemailer pra vocês poderem testar local.

![image](https://github.com/livnascimento/desafio-m05-b2bt05-equipe-19/assets/51425339/c0f3e5b2-318a-4ec2-8625-cabdd7aad503)
