### ISSUE TITLE
Bug em ListCategories

### ISSUE THREAD

**Issue by livnascimento** [livnascimento/desafio-m05-b2bt05-equipe-19#6]
A rota estava sem o middleware e agora que eu adicionei, ela não está funcionando sem filtro. Vou deixar uma fotinha do insomnia aqui, Lu. (eu acho que foi você quem fez essa parte - viva minha memória de peixe! - se foi Vitória me avisa que eu passo a issue pra ela )

![image](https://github.com/livnascimento/desafio-m05-b2bt05-equipe-19/assets/51425339/ddd91898-6197-4824-8e5a-350ac118b174)

**Comment by LuhOli42** [comment]
Oie, quem fez listar categorias foi  a vitória, pelo q lembre. Mas pelo código, me parece que ta filtrando por id a query, sendo q era pra listar todas não?

**Comment by LuhOli42** [comment]
Arrumei, vc colocou um verify categorias, mas para listar categorias, n precisa verificar se tinha id.

**Comment by livnascimento** [comment]
amiga KKKKKKKKKKKKKKKKKKKKKKKKJJJJJKKKKKKKKKKKKKK
desculpa, eu brisei demais aí
