### ISSUE TITLE
Atualizar Cliente

### ISSUE THREAD

**Issue by LuhOli42** [livnascimento/desafio-m05-b2bt05-equipe-19#8]
1. Quando tento atualizar só o numero ou cep, o numero no banco de dados e o endereço não são atualizado.
2. Quando tento atualizar usando um email q ja existe no banco de dados ele retorna erro interno do servidor, em vez de avisar q esse email ja existe no banco de dados.

**Comment by livnascimento** [comment]
Desculpa a demora pra vir ver as issues, eu tava na reunião com Isa. Vou verificar isso ainda hoje, tá bem? Obrigada por abrir as issues, vai facilitar bastante!
